name: UserStyles.org Auto Update

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
    inputs:
      tags:
        description: "."

jobs:
  auto-update-uso:
    runs-on: ubuntu-latest

    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm i

      - name: Update
        id: update
        run: node updater.js

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.update.outputs.changes }}
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
          skip_dirty_check: true
