name: Handle Update/Add Request Issue

on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v1
        if: github.event.issue.labels[0].name == 'update/add style from uso' || github.event.issue.labels[0].name == 'update/add usercss'

      - name: Checkout
        uses: actions/checkout@v2
        if: github.event.issue.labels[0].name == 'update/add style from uso' || github.event.issue.labels[0].name == 'update/add usercss'
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        if: github.event.issue.labels[0].name == 'update/add style from uso' || github.event.issue.labels[0].name == 'update/add usercss'
        with:
          node-version: 14.x

      - name: Install Dependencies
        if: github.event.issue.labels[0].name == 'update/add style from uso' || github.event.issue.labels[0].name == 'update/add usercss'
        run: npm i

      - name: Update/add from userstyles.org
        id: uso
        run: node handle-issue.js uso
        if: github.event.issue.labels[0].name == 'update/add style from uso'
        env:
          ISSUE_DATA: ${{toJSON(github.event.issue)}}

      - name: Update/add usercss
        id: usercss
        run: node handle-issue.js usercss
        if: github.event.issue.labels[0].name == 'update/add usercss'
        env:
          ISSUE_DATA: ${{toJSON(github.event.issue)}}

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.issue.labels[0].name == 'update/add style from uso'
        with:
          commit_message: ${{ steps.uso.outputs.changes }}${{ steps.usercss.outputs.changes }}
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
          skip_dirty_check: true
